### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by krussedull** [Siddhart/Twitch-Notification-Discord-Bot#9]
C:\DiscordBots\TwitchBot>node index.js
Logged in as |NLAS|Twitch#8019!
C:\DiscordBots\TwitchBot\index.js:27
        if (StreamData.data.length == 0) return
                            ^

TypeError: Cannot read property 'length' of undefined
    at C:\DiscordBots\TwitchBot\index.js:27:29
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

C:\DiscordBots\TwitchBot>node index.js
Logged in as |NLAS|Twitch#8019!
C:\DiscordBots\TwitchBot\index.js:27
        if (StreamData.data.length == 0) return
                            ^

TypeError: Cannot read property 'length' of undefined
    at C:\DiscordBots\TwitchBot\index.js:27:29
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by Siddhart** [comment]
Hey, The StreamData variable will only have a value of undefined if the given values are not correct. The "ChannelName" value in the config.json should be the name that is in the url of the streamer's twitch page ([check this part](https://github.com/Siddhartt/Twitch-Notification-Discord-Bot/blob/main/README.md#add-streamers)). Also make sure that you assigned the correct twitch_clientID and twitch_secret. If it still didnt work let me know :D

**Comment by krussedull** [comment]
silly me i had put in the hole link of my user, working now, if i coude come whit one sugestion?
when the stream is ended , can the status update to stream endet? and a summary if posible

**Comment by Siddhart** [comment]
Hmm that sounds like a good suggestion. I will see if i can add it soon.. after my exams :D
